CREATE DATABASE CakeShop
GO

USE CakeShop
GO

CREATE TABLE USUARIO (
	ID INT PRIMARY KEY,
	NOME VARCHAR(100),
	LOGINUSUARIO VARCHAR(20),
	SENHA VARCHAR(10), 
	EMAIL VARCHAR(200)
);

CREATE TABLE CLIENTE (
	ID_CLIENTE INTEGER PRIMARY KEY IDENTITY(1,1),
	NOME_CLIENTE VARCHAR(200),
	TELEFONE VARCHAR(50),
	EMAIL VARCHAR(250),
	LOGIN_CLIENTE VARCHAR(50),
	SENHA VARCHAR(8),
	ENDERECO VARCHAR(300),
	NUMERO VARCHAR(50),
	COMPLEMENTO VARCHAR(100),
	CEP VARCHAR(50),
	CIDADE VARCHAR(50),
	ESTADO CHAR(3)
);

CREATE TABLE UNIDADEDEMEDIDA (
	ID INT PRIMARY KEY IDENTITY(1,1),
	NOME VARCHAR(20),
	SIGLA CHAR(3)
);

CREATE TABLE CATEGORIA (
	ID INT PRIMARY KEY IDENTITY(1,1),
	NOME VARCHAR(10)
);

INSERT INTO CATEGORIA (NOME) VALUES ('DOCES'), ( 'SALGADOS'), ( 'BOLOS');

CREATE TABLE PRODUTO (
	ID_PRODUTO INT PRIMARY KEY IDENTITY(1,1),
	NOME_PRODUTO VARCHAR(200),
	PRECO DECIMAL(10,2),
	ID_UNIDADEDEMEDIDA INT REFERENCES UNIDADEDEMEDIDA (ID),
	ID_CATEGORIA INT REFERENCES CATEGORIA (ID),
	DESCRICAO VARCHAR(MAX),
	FOTO VARCHAR(2000)
);

CREATE TABLE PEDIDO (
	ID_PEDIDO INT PRIMARY KEY IDENTITY(1,1),
	ID_CLIENTE INT REFERENCES CLIENTE (ID_CLIENTE),
	DATAPEDIDO DATETIME NOT NULL DEFAULT GETDATE(),
	DATAENTREGA DATETIME,
	[STATUS] INTEGER
);

CREATE TABLE ITEM_PEDIDO (
	ID_ITEM_PEDIDO INT PRIMARY KEY IDENTITY(1,1),
	ID_PEDIDO INT REFERENCES PEDIDO (ID_PEDIDO),
	ID_PRODUTO INT REFERENCES PRODUTO (ID_PRODUTO),
	PRECO DECIMAL(10,2),
	QTD_ITEM_PRODUTO INT
);